# Generated by Django 2.0.4 on 2018-04-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='play_duration',
            field=models.DurationField(default=0, editable=False),
        ),
    ]
