# Generated by Django 2.0.4 on 2018-04-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20180425_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='play_duration',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
